version: "3"

services:
  hdd-socomec-db:
    container_name: hdd-socomec-db
    build:
      context: ./postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_HDD_SOCOMEC_USER=hdd
      - PG_HDD_SOCOMEC_PASSWORD=hdd
    ports:
      - "5436:5432"
    volumes:
      - hdd-socomec-pgdata:/var/lib/postgresql/data

  hdd-socomec-metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - hdd-socomec-metabase:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: hdd-socomec-db
    depends_on:
      - hdd-socomec-db
    links:
      - hdd-socomec-db

volumes:
  hdd-socomec-pgdata:
  hdd-socomec-metabase:
